### ISSUE TITLE
MiaowShow-master/MiaowShow/MiaowShow/Classes/Resource/PrefixHeader.pch:24:9: 'IJKMediaFramework/IJKMediaFramework.h' file not found

### ISSUE THREAD

**Issue by ajaybeniwal** [SunLiner/MiaowShow#3]
/Users/<username>/Development/MiaowShow-master/MiaowShow/MiaowShow/Classes/Resource/PrefixHeader.pch:24:9: 'IJKMediaFramework/IJKMediaFramework.h' file not found

**Comment by SunLiner** [comment]
Please read my blog carefully :  [blog](http://www.jianshu.com/p/b8db6c142aad)
